
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView display;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.Table table2;

	private global::Gtk.Button clear;

	private global::Gtk.Button divide;

	private global::Gtk.Button doubleZero;

	private global::Gtk.Button eight;

	private global::Gtk.Button equal;

	private global::Gtk.Button five;

	private global::Gtk.Button four;

	private global::Gtk.Button leftParentheses;

	private global::Gtk.Button minus;

	private global::Gtk.Button nine;

	private global::Gtk.Button one;

	private global::Gtk.Button plus;

	private global::Gtk.Button rightParentheses;

	private global::Gtk.Button seven;

	private global::Gtk.Button six;

	private global::Gtk.Button three;

	private global::Gtk.Button times;

	private global::Gtk.Button tripleZero;

	private global::Gtk.Button two;

	private global::Gtk.Button zero;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.display = new global::Gtk.TextView();
		this.display.CanFocus = true;
		this.display.Name = "display";
		this.display.Editable = false;
		this.GtkScrolledWindow.Add(this.display);
		this.vbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w3 = new global::Gtk.Viewport();
		w3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table(((uint)(4)), ((uint)(5)), true);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(8));
		this.table2.ColumnSpacing = ((uint)(12));
		// Container child table2.Gtk.Table+TableChild
		this.clear = new global::Gtk.Button();
		this.clear.CanFocus = true;
		this.clear.Name = "clear";
		this.clear.UseUnderline = true;
		this.clear.Label = global::Mono.Unix.Catalog.GetString("C");
		this.table2.Add(this.clear);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.clear]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(4));
		w4.RightAttach = ((uint)(5));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.divide = new global::Gtk.Button();
		this.divide.CanFocus = true;
		this.divide.Name = "divide";
		this.divide.UseUnderline = true;
		this.divide.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table2.Add(this.divide);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.divide]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(4));
		w5.RightAttach = ((uint)(5));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.doubleZero = new global::Gtk.Button();
		this.doubleZero.CanFocus = true;
		this.doubleZero.Name = "doubleZero";
		this.doubleZero.UseUnderline = true;
		this.doubleZero.Label = global::Mono.Unix.Catalog.GetString("00");
		this.table2.Add(this.doubleZero);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.doubleZero]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.eight = new global::Gtk.Button();
		this.eight.CanFocus = true;
		this.eight.Name = "eight";
		this.eight.UseUnderline = true;
		this.eight.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table2.Add(this.eight);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2[this.eight]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.equal = new global::Gtk.Button();
		this.equal.CanFocus = true;
		this.equal.Name = "equal";
		this.equal.UseUnderline = true;
		this.equal.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table2.Add(this.equal);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2[this.equal]));
		w8.TopAttach = ((uint)(3));
		w8.BottomAttach = ((uint)(4));
		w8.LeftAttach = ((uint)(3));
		w8.RightAttach = ((uint)(4));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.five = new global::Gtk.Button();
		this.five.CanFocus = true;
		this.five.Name = "five";
		this.five.UseUnderline = true;
		this.five.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table2.Add(this.five);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2[this.five]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.four = new global::Gtk.Button();
		this.four.CanFocus = true;
		this.four.Name = "four";
		this.four.UseUnderline = true;
		this.four.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table2.Add(this.four);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2[this.four]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.leftParentheses = new global::Gtk.Button();
		this.leftParentheses.CanFocus = true;
		this.leftParentheses.Name = "leftParentheses";
		this.leftParentheses.UseUnderline = true;
		this.leftParentheses.Label = global::Mono.Unix.Catalog.GetString("(");
		this.table2.Add(this.leftParentheses);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2[this.leftParentheses]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(3));
		w11.RightAttach = ((uint)(4));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.minus = new global::Gtk.Button();
		this.minus.CanFocus = true;
		this.minus.Name = "minus";
		this.minus.UseUnderline = true;
		this.minus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table2.Add(this.minus);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2[this.minus]));
		w12.LeftAttach = ((uint)(4));
		w12.RightAttach = ((uint)(5));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.nine = new global::Gtk.Button();
		this.nine.CanFocus = true;
		this.nine.Name = "nine";
		this.nine.UseUnderline = true;
		this.nine.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table2.Add(this.nine);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2[this.nine]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(2));
		w13.RightAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.one = new global::Gtk.Button();
		this.one.CanFocus = true;
		this.one.Name = "one";
		this.one.UseUnderline = true;
		this.one.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table2.Add(this.one);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2[this.one]));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.plus = new global::Gtk.Button();
		this.plus.CanFocus = true;
		this.plus.Name = "plus";
		this.plus.UseUnderline = true;
		this.plus.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table2.Add(this.plus);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2[this.plus]));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.rightParentheses = new global::Gtk.Button();
		this.rightParentheses.CanFocus = true;
		this.rightParentheses.Name = "rightParentheses";
		this.rightParentheses.UseUnderline = true;
		this.rightParentheses.Label = global::Mono.Unix.Catalog.GetString(")");
		this.table2.Add(this.rightParentheses);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2[this.rightParentheses]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(4));
		w16.RightAttach = ((uint)(5));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.seven = new global::Gtk.Button();
		this.seven.CanFocus = true;
		this.seven.Name = "seven";
		this.seven.UseUnderline = true;
		this.seven.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table2.Add(this.seven);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2[this.seven]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.six = new global::Gtk.Button();
		this.six.CanFocus = true;
		this.six.Name = "six";
		this.six.UseUnderline = true;
		this.six.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table2.Add(this.six);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2[this.six]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(2));
		w18.RightAttach = ((uint)(3));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.three = new global::Gtk.Button();
		this.three.CanFocus = true;
		this.three.Name = "three";
		this.three.UseUnderline = true;
		this.three.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table2.Add(this.three);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2[this.three]));
		w19.LeftAttach = ((uint)(2));
		w19.RightAttach = ((uint)(3));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.times = new global::Gtk.Button();
		this.times.CanFocus = true;
		this.times.Name = "times";
		this.times.UseUnderline = true;
		this.times.Label = global::Mono.Unix.Catalog.GetString("*");
		this.table2.Add(this.times);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2[this.times]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.LeftAttach = ((uint)(3));
		w20.RightAttach = ((uint)(4));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.tripleZero = new global::Gtk.Button();
		this.tripleZero.CanFocus = true;
		this.tripleZero.Name = "tripleZero";
		this.tripleZero.UseUnderline = true;
		this.tripleZero.Label = global::Mono.Unix.Catalog.GetString("000");
		this.table2.Add(this.tripleZero);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2[this.tripleZero]));
		w21.TopAttach = ((uint)(3));
		w21.BottomAttach = ((uint)(4));
		w21.LeftAttach = ((uint)(2));
		w21.RightAttach = ((uint)(3));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.two = new global::Gtk.Button();
		this.two.CanFocus = true;
		this.two.Name = "two";
		this.two.UseUnderline = true;
		this.two.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table2.Add(this.two);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2[this.two]));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.zero = new global::Gtk.Button();
		this.zero.CanFocus = true;
		this.zero.Name = "zero";
		this.zero.UseUnderline = true;
		this.zero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.table2.Add(this.zero);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2[this.zero]));
		w23.TopAttach = ((uint)(3));
		w23.BottomAttach = ((uint)(4));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		w3.Add(this.table2);
		this.GtkScrolledWindow1.Add(w3);
		this.vbox2.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
		w26.Position = 1;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 321;
		this.DefaultHeight = 410;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
