
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview5;

	private global::Gtk.HBox firstLayer;

	private global::Gtk.Button one;

	private global::Gtk.Button two;

	private global::Gtk.Button three;

	private global::Gtk.Button plus;

	private global::Gtk.Button minus;

	private global::Gtk.HBox secondLayer;

	private global::Gtk.Button four;

	private global::Gtk.Button five;

	private global::Gtk.Button six;

	private global::Gtk.Button times;

	private global::Gtk.Button divide;

	private global::Gtk.HBox thirdLayer;

	private global::Gtk.Button seven;

	private global::Gtk.Button eight;

	private global::Gtk.Button nine;

	private global::Gtk.Button leftParentheses;

	private global::Gtk.Button rightParentheses;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button zero;

	private global::Gtk.Button equal;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview5 = new global::Gtk.TextView();
		this.textview5.CanFocus = true;
		this.textview5.Name = "textview5";
		this.GtkScrolledWindow.Add(this.textview5);
		this.vbox2.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.firstLayer = new global::Gtk.HBox();
		this.firstLayer.Name = "firstLayer";
		this.firstLayer.Spacing = 6;
		// Container child firstLayer.Gtk.Box+BoxChild
		this.one = new global::Gtk.Button();
		this.one.CanFocus = true;
		this.one.Name = "one";
		this.one.UseUnderline = true;
		this.one.Label = global::Mono.Unix.Catalog.GetString("1");
		this.firstLayer.Add(this.one);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.firstLayer[this.one]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child firstLayer.Gtk.Box+BoxChild
		this.two = new global::Gtk.Button();
		this.two.CanFocus = true;
		this.two.Name = "two";
		this.two.UseUnderline = true;
		this.two.Label = global::Mono.Unix.Catalog.GetString("2");
		this.firstLayer.Add(this.two);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.firstLayer[this.two]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child firstLayer.Gtk.Box+BoxChild
		this.three = new global::Gtk.Button();
		this.three.CanFocus = true;
		this.three.Name = "three";
		this.three.UseUnderline = true;
		this.three.Label = global::Mono.Unix.Catalog.GetString("3");
		this.firstLayer.Add(this.three);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.firstLayer[this.three]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child firstLayer.Gtk.Box+BoxChild
		this.plus = new global::Gtk.Button();
		this.plus.CanFocus = true;
		this.plus.Name = "plus";
		this.plus.UseUnderline = true;
		this.plus.Label = global::Mono.Unix.Catalog.GetString("+");
		this.firstLayer.Add(this.plus);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.firstLayer[this.plus]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		// Container child firstLayer.Gtk.Box+BoxChild
		this.minus = new global::Gtk.Button();
		this.minus.CanFocus = true;
		this.minus.Name = "minus";
		this.minus.UseUnderline = true;
		this.minus.Label = global::Mono.Unix.Catalog.GetString("-");
		this.firstLayer.Add(this.minus);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.firstLayer[this.minus]));
		w7.Position = 4;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox2.Add(this.firstLayer);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.firstLayer]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.secondLayer = new global::Gtk.HBox();
		this.secondLayer.Name = "secondLayer";
		this.secondLayer.Spacing = 6;
		// Container child secondLayer.Gtk.Box+BoxChild
		this.four = new global::Gtk.Button();
		this.four.CanFocus = true;
		this.four.Name = "four";
		this.four.UseUnderline = true;
		this.four.Label = global::Mono.Unix.Catalog.GetString("4");
		this.secondLayer.Add(this.four);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.secondLayer[this.four]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child secondLayer.Gtk.Box+BoxChild
		this.five = new global::Gtk.Button();
		this.five.CanFocus = true;
		this.five.Name = "five";
		this.five.UseUnderline = true;
		this.five.Label = global::Mono.Unix.Catalog.GetString("5");
		this.secondLayer.Add(this.five);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.secondLayer[this.five]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child secondLayer.Gtk.Box+BoxChild
		this.six = new global::Gtk.Button();
		this.six.CanFocus = true;
		this.six.Name = "six";
		this.six.UseUnderline = true;
		this.six.Label = global::Mono.Unix.Catalog.GetString("6");
		this.secondLayer.Add(this.six);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.secondLayer[this.six]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child secondLayer.Gtk.Box+BoxChild
		this.times = new global::Gtk.Button();
		this.times.CanFocus = true;
		this.times.Name = "times";
		this.times.UseUnderline = true;
		this.times.Label = global::Mono.Unix.Catalog.GetString("*");
		this.secondLayer.Add(this.times);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.secondLayer[this.times]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child secondLayer.Gtk.Box+BoxChild
		this.divide = new global::Gtk.Button();
		this.divide.CanFocus = true;
		this.divide.Name = "divide";
		this.divide.UseUnderline = true;
		this.divide.Label = global::Mono.Unix.Catalog.GetString("/");
		this.secondLayer.Add(this.divide);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.secondLayer[this.divide]));
		w13.Position = 4;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox2.Add(this.secondLayer);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.secondLayer]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.thirdLayer = new global::Gtk.HBox();
		this.thirdLayer.Name = "thirdLayer";
		this.thirdLayer.Spacing = 6;
		// Container child thirdLayer.Gtk.Box+BoxChild
		this.seven = new global::Gtk.Button();
		this.seven.CanFocus = true;
		this.seven.Name = "seven";
		this.seven.UseUnderline = true;
		this.seven.Label = global::Mono.Unix.Catalog.GetString("7");
		this.thirdLayer.Add(this.seven);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.thirdLayer[this.seven]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child thirdLayer.Gtk.Box+BoxChild
		this.eight = new global::Gtk.Button();
		this.eight.CanFocus = true;
		this.eight.Name = "eight";
		this.eight.UseUnderline = true;
		this.eight.Label = global::Mono.Unix.Catalog.GetString("8");
		this.thirdLayer.Add(this.eight);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.thirdLayer[this.eight]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child thirdLayer.Gtk.Box+BoxChild
		this.nine = new global::Gtk.Button();
		this.nine.CanFocus = true;
		this.nine.Name = "nine";
		this.nine.UseUnderline = true;
		this.nine.Label = global::Mono.Unix.Catalog.GetString("9");
		this.thirdLayer.Add(this.nine);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.thirdLayer[this.nine]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child thirdLayer.Gtk.Box+BoxChild
		this.leftParentheses = new global::Gtk.Button();
		this.leftParentheses.CanFocus = true;
		this.leftParentheses.Name = "leftParentheses";
		this.leftParentheses.UseUnderline = true;
		this.leftParentheses.Label = global::Mono.Unix.Catalog.GetString("(");
		this.thirdLayer.Add(this.leftParentheses);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.thirdLayer[this.leftParentheses]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		// Container child thirdLayer.Gtk.Box+BoxChild
		this.rightParentheses = new global::Gtk.Button();
		this.rightParentheses.CanFocus = true;
		this.rightParentheses.Name = "rightParentheses";
		this.rightParentheses.UseUnderline = true;
		this.rightParentheses.Label = global::Mono.Unix.Catalog.GetString(")");
		this.thirdLayer.Add(this.rightParentheses);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.thirdLayer[this.rightParentheses]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox2.Add(this.thirdLayer);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.thirdLayer]));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.zero = new global::Gtk.Button();
		this.zero.CanFocus = true;
		this.zero.Name = "zero";
		this.zero.UseUnderline = true;
		this.zero.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox3.Add(this.zero);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.zero]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.equal = new global::Gtk.Button();
		this.equal.CanFocus = true;
		this.equal.Name = "equal";
		this.equal.UseUnderline = true;
		this.equal.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox3.Add(this.equal);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.equal]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w23.Position = 4;
		w23.Expand = false;
		w23.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 326;
		this.DefaultHeight = 340;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
