
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label h1;

	private global::Gtk.Label h2;

	private global::Gtk.Label label8;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Label label1;

	private global::Gtk.Entry amount;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Label label2;

	private global::Gtk.ComboBoxEntry comboBoxFrom;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Label label7;

	private global::Gtk.Button switchCurrency;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Label label3;

	private global::Gtk.ComboBoxEntry comboBoxTo;

	private global::Gtk.VBox vbox8;

	private global::Gtk.Label result;

	private global::Gtk.Entry entry2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button convert;

	private global::Gtk.Button clear;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.h1 = new global::Gtk.Label();
		this.h1.Name = "h1";
		this.h1.LabelProp = global::Mono.Unix.Catalog.GetString("Currency Converter");
		this.vbox2.Add(this.h1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.h1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.h2 = new global::Gtk.Label();
		this.h2.Name = "h2";
		this.h2.LabelProp = global::Mono.Unix.Catalog.GetString("Converted Currency");
		this.vbox2.Add(this.h2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.h2]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.vbox1.Add(this.label8);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label8]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Enter Amount :");
		this.vbox4.Add(this.label1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.amount = new global::Gtk.Entry();
		this.amount.CanFocus = true;
		this.amount.Name = "amount";
		this.amount.IsEditable = true;
		this.amount.InvisibleChar = '•';
		this.vbox4.Add(this.amount);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.amount]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.hbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("From :");
		this.vbox5.Add(this.label2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label2]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.comboBoxFrom = global::Gtk.ComboBoxEntry.NewText();
		this.comboBoxFrom.Name = "comboBoxFrom";
		this.vbox5.Add(this.comboBoxFrom);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.comboBoxFrom]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox1.Add(this.vbox5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox5]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Switch");
		this.vbox7.Add(this.label7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label7]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.switchCurrency = new global::Gtk.Button();
		this.switchCurrency.CanFocus = true;
		this.switchCurrency.Name = "switchCurrency";
		this.switchCurrency.UseUnderline = true;
		this.switchCurrency.Label = global::Mono.Unix.Catalog.GetString("change");
		this.vbox7.Add(this.switchCurrency);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.switchCurrency]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox1.Add(this.vbox7);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox7]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("To :");
		this.vbox6.Add(this.label3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label3]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.comboBoxTo = global::Gtk.ComboBoxEntry.NewText();
		this.comboBoxTo.Name = "comboBoxTo";
		this.vbox6.Add(this.comboBoxTo);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.comboBoxTo]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox1.Add(this.vbox6);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox6]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.result = new global::Gtk.Label();
		this.result.Name = "result";
		this.result.LabelProp = global::Mono.Unix.Catalog.GetString("result");
		this.vbox8.Add(this.result);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.result]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.vbox8.Add(this.entry2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.entry2]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.hbox1.Add(this.vbox8);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox8]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.convert = new global::Gtk.Button();
		this.convert.CanFocus = true;
		this.convert.Name = "convert";
		this.convert.UseUnderline = true;
		this.convert.Label = global::Mono.Unix.Catalog.GetString("Convert");
		this.hbox2.Add(this.convert);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.convert]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.clear = new global::Gtk.Button();
		this.clear.CanFocus = true;
		this.clear.Name = "clear";
		this.clear.UseUnderline = true;
		this.clear.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.hbox2.Add(this.clear);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.clear]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 879;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
